### ISSUE TITLE
Upload .streamDeckPlugin to GH Releases

### ISSUE THREAD

**Issue by AlexHedley** [AlexHedley/streamdeckplugindistribution-test-action#4]
Should this be in another action?
Or just an option in this one

```yml
upload: true #default false
destination: GHR / Elgato Store
```

**Comment by AlexHedley** [comment]
```yml
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./my-artifact.zip
          asset_name: my-artifact.zip
          asset_content_type: application/zip
```

actions/upload-release-asset@v1
- https://github.com/actions/upload-release-asset

actions/create-release@v1
- https://github.com/actions/create-release

actions/upload-artifact@v2
- https://github.com/actions/upload-artifact

GitHub Releases
- https://david.gardiner.net.au/2020/07/github-release.html
